from enum import Enum

class Gender(str, Enum):
    MALE = "MALE"
    FEMALE = "FEMALE"
    OTHER = "OTHER"

class Subjects(str, Enum):
    PHYSICS = "PHYSICS"
    CHEMISTRY = "CHEMISTRY"
    MATHEMATICS = "MATHEMATICS"
    BIOLOGY = "BIOLOGY"

    ECONOMICS = "ECONOMICS"
    ACCOUNTANCY = "ACCOUNTANCY"
    BUSINESS_STUDIES = "BUSINESS STUDIES"

    ENGLISH = "ENGLISH"
    HISTORY = "HISTORY"
    GEOGRAPHY = "GEOGRAPHY"
    POLITICAL_SCIENCE = "POLITICAL SCIENCE"
    SOCIOLOGY = "SOCIOLOGY"
    PSYCHOLOGY = "PSYCHOLOGY"

class Course(str, Enum):
    COMPUTER_SCIENCE_ENGINEERING = "COMPUTER SCIENCE ENGINEERING"
    MECHANICAL_ENGINEERING = "MECHANICAL ENGINEERING"
    ELECTRICAL_ENGINEERING = "ELECTRICAL ENGINEERING"
    CIVIL_ENGINEERING = "CIVIL ENGINEERING"
    ELECTRONICS_AND_COMMUNICATION_ENGINEERING = "ELECTRONICS AND COMMUNICATION ENGINEERING"
    
    MBBS = "MBBS"
    BDS_DENTISTRY = "BDS (DENTISTRY)"
    BAMS_AYURVEDA = "BAMS (AYURVEDA)"
    BHMS_HOMEOPATHY = "BHMS (HOMEOPATHY)"
    BPT_PHYSIOTHERAPY = "BPT (PHYSIOTHERAPY)"
    
    B_COM = "B.COM"
    BBA = "BBA"
    BBM = "BBM"
    CA_CHARTERED_ACCOUNTANCY = "CA (CHARTERED ACCOUNTANCY)"
    
    BA_IN_HISTORY = "BA IN HISTORY"
    BA_IN_PSYCHOLOGY = "BA IN PSYCHOLOGY"
    BA_IN_SOCIOLOGY = "BA IN SOCIOLOGY"
    BA_IN_POLITICAL_SCIENCE = "BA IN POLITICAL SCIENCE"
    BA_IN_ENGLISH = "BA IN ENGLISH"
